pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    tools {
        maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                echo '------ Building ------'
                sh 'mvn -B -DskipTests clean compile'
            }
        }
        stage('Test') {
            steps {
                echo '------ Testing ------'
                sh 'mvn test'
            }
            /*post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }*/
        }
        stage('SonarQube') {
            steps {
                echo'------ SonarQube ------'
                def mvn = tool 'Maven';
                withSonarQubeEnv() {
                      sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=test -Dsonar.projectName='test'"
                }
                
            }
        }
        stage('Deploy') {
            steps {
                echo '------ Deploying ------'
                //sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
